require:
  - rubocop-performance
  - rubocop-minitest
  
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/StringLiterals:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Layout/LineLength:
  Max: 120
