name: Ruby

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [3.1,3.2]

    steps:
    - uses: actions/checkout@v3.5.3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Runs the default task (tests + rubocop)
      run: bundle exec rake